FROM python:3.11

ARG PROJECTPATH

RUN mkdir /app
COPY ${PROJECTPATH}/internals /app
COPY ${PROJECTPATH}/scripts/requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install pytest
RUN pip install -r ./requirements.txt
ENV PYTHONPATH "${PYTHONPATH}:/app"

ENTRYPOINT [ "pytest" ]
CMD [ "-v" ]
